available_text_models: ["llama3.3-70b-instruct"]
# "gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-4-turbo", "gpt-4-vision-preview", "gpt-4", "text-davinci-003",
info:
  llama3.3-70b-instruct:
    type: chat_completion
    name: llama3.3
    description:  
      en: Llama.3. 70B trained   It's <b>conversational</b> and <b>knowledgeable</b>. Ideal for discussions and explanations. If there are some topics it can't cover, try asking me about <b>education and learning materials</b>..
      ru: Llama.3.3 70 млрд токенов   Это <b> разговорная </b> языковая модель. Идеально подходит для дискуссий и объяснений. Если есть какие-то темы, которые он не может охватить, попробуйте спросить меня об образовании и учебных материалах..
    price_per_1000_input_tokens: 0.00065
    price_per_1000_output_tokens: 0.00065
    tokens_per_symbol: 0.75
    context_window_size: 2048 #  131072 = 128k tokens
    scores:
      Smart: 5
      Fast: 4
      Cheap: 5

  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description:  
      en: ChatGPT is that well-known model. It's <b>fast</b> and <b>cheap</b>. Ideal for everyday tasks. If there are some tasks it can't handle, try the <b>GPT-4</b>.
    price_per_1000_input_tokens: 0.0015
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-3.5-turbo-16k:
    type: chat_completion
    name: GPT-16K
    description:  
      en: ChatGPT is that well-known model. It's <b>fast</b> and <b>cheap</b>. Ideal for everyday tasks. If there are some tasks it can't handle, try the <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description:  
      en: GPT-4 is the <b>smartest</b> and most advanced model in the world. But it is slower and not as cost-efficient as ChatGPT. Best choice for <b>complex</b> intellectual tasks.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  gpt-4-turbo:
    type: chat_completion
    name: GPT-4 Turbo
    description:  
      en: GPT-4 Turbo is a <b>faster</b> and <b>cheaper</b> version of GPT-4. It's as smart as GPT-4, so you should use it instead of GPT-4.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  gpt-4-vision-preview:
    type: chat_completion
    name: GPT-4 Vision
    description:  
      en: Ability to <b>understand images</b>, in addition to all other GPT-4 Turbo capabilties.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3
  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description:  
      en: GPT-4o is a special variant of GPT-4 designed for optimal performance and accuracy. Suitable for complex and detailed tasks.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      smart: 5
      fast: 2
      cheap: 2

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description:  
      en: GPT-3.5 is a legacy model. Actually there is <b>no reason to use it</b>, because it is more expensive and slower than ChatGPT, but just about as smart.

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  dalle-2:
    type: image
    price_per_1_image: 0.018 # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006

gpt-4-turbo:
  type: chat_completion
  name: GPT-4-turbo
  description:  
    en: GPT-4 Turbo is an optimized version of GPT-4 - one the <b>smartest</b> and most advanced model in the world, offering lower costs per token processing and an increased token limit (up to 128k tokens), making it preferable for tasks that require longer contexts and faster performance.
    ru: Оптимизированная версия GPT-4 (одна из наиболее продвинутых моделей в мире), обладающая меньшей стоимостью за обработку токенов и увеличенным лимитом (вплоть до 128k токенов), что делает её предпочтительной для задач, где необходимы более длинные контексты и скорость выполнения.

  price_per_1000_input_tokens: 0.012
  price_per_1000_output_tokens: 0.024
  scores:
    smart: 4
    fast: 4
    cheap: 3
